name: ğŸ”¨ Build Project

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ’  Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: ğŸ“‚ Checkout Project
        uses: actions/checkout@v4

      - name: â¬‡ï¸ Install Dependencies
        run: |
          yarn

      - name: ğŸ”¨ Build Project
        run: |
          yarn build
        env:
          NEXT_PUBLIC_API_ENDPOINT: ${{ vars.NEXT_PUBLIC_API_ENDPOINT }}

        # - name: ğŸ”— Zip Files
        #   run: cd out && tar -cvf wit-site-build.zip *

      - name: â¬†ï¸ Upload Build
        uses: actions/upload-artifact@v4
        with:
          name: wit-site-build
          path: out
